services:
  db:
    image: postgres:18
    container_name: magazord_db
    environment:
      - POSTGRES_DB=magazord
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
